/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package distribucion;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Adri
 */
public class ClienteInterfaz extends javax.swing.JFrame {

    private JTextField[] jTextVehiculos;
    private JTextField[] jTextOperarios;
    private JLabel[] iconosVehiculos;
    private JLabel[] iconosOperarios;

    public ClienteInterfaz() {
        Conexion conexion = new Conexion(this);
        initComponents();
        conexion.start();

        this.jTextVehiculos = new JTextField[]{su1, su2, su3, su4, su5, su6, su7, su8};
        this.jTextOperarios = new JTextField[]{op1, op2, op3, op4, op5, op6, op7, op8};
        this.iconosVehiculos = new JLabel[]{iv1, iv2, iv3, iv4, iv5, iv6, iv7, iv8};
        this.iconosOperarios = new JLabel[]{io1, io2, io3, io4, io5, io6, io7, io8};
    }

    //Muestra en la interfaz la fila de coches en espera
    public void escribirEntradaVehiculos(ArrayList<String> vehiculosEntrada) {
        if (vehiculosEntrada.isEmpty()){
            jTextFieldCochesEsperando.setText("Cola de espera vacía");
        } else {
            jTextFieldCochesEsperando.setText(vehiculosEntrada.toString());
        }
    }

    //Muestra en la interfaz los vehiculos de cada surtidor
    public void escribirSurtidores(ArrayList<String> vehiculosSurtidor) {
        for (int i = 0; i < jTextVehiculos.length; i++) {
            jTextVehiculos[i].setText(vehiculosSurtidor.get(i));
            if(vehiculosSurtidor.get(i).equals("")){
                iconosVehiculos[i].setEnabled(false);
            } else {
                iconosVehiculos[i].setEnabled(true);
            }
        }
    }

    public void escribirOperarios(ArrayList<String> operariosSurtidor) {
        for (int i = 0; i < jTextOperarios.length; i++) {
            jTextOperarios[i].setText(operariosSurtidor.get(i));
            if(operariosSurtidor.get(i).equals("")){
                iconosOperarios[i].setEnabled(false);
            } else {
                iconosOperarios[i].setEnabled(true);
            }
        }
    }

    //Método que recoge el icono para su uso en la ventana
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCochesEsperando = new javax.swing.JTextField();
        su6 = new javax.swing.JTextField();
        su3 = new javax.swing.JTextField();
        su4 = new javax.swing.JTextField();
        su5 = new javax.swing.JTextField();
        su7 = new javax.swing.JTextField();
        su8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        op1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        op2 = new javax.swing.JTextField();
        op3 = new javax.swing.JTextField();
        op4 = new javax.swing.JTextField();
        op5 = new javax.swing.JTextField();
        op6 = new javax.swing.JTextField();
        op7 = new javax.swing.JTextField();
        op8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        su2 = new javax.swing.JTextField();
        su1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        io4 = new javax.swing.JLabel();
        iv2 = new javax.swing.JLabel();
        iv3 = new javax.swing.JLabel();
        iv4 = new javax.swing.JLabel();
        iv5 = new javax.swing.JLabel();
        iv6 = new javax.swing.JLabel();
        iv7 = new javax.swing.JLabel();
        iv8 = new javax.swing.JLabel();
        iv1 = new javax.swing.JLabel();
        io8 = new javax.swing.JLabel();
        io2 = new javax.swing.JLabel();
        io3 = new javax.swing.JLabel();
        io1 = new javax.swing.JLabel();
        io5 = new javax.swing.JLabel();
        io6 = new javax.swing.JLabel();
        io7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente Gasolinera");
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(400, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCochesEsperando.setEditable(false);
        getContentPane().add(jTextFieldCochesEsperando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 970, 30));

        su6.setEditable(false);
        su6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 130, 40));

        su3.setEditable(false);
        su3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 130, 40));

        su4.setEditable(false);
        su4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 130, 40));

        su5.setEditable(false);
        su5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 130, 40));

        su7.setEditable(false);
        su7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 130, 40));

        su8.setEditable(false);
        su8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 130, 40));

        jLabel1.setText("Surtidor 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, -1));

        jLabel2.setText("Surtidor 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 90, -1));

        jLabel3.setText("Surtidor 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 90, -1));

        jLabel4.setText("Surtidor 4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, 90, -1));

        jLabel5.setText("Surtidor 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, -1));

        jLabel6.setText("Surtidor 6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 90, -1));

        jLabel7.setText("Surtidor 7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 90, -1));

        jLabel8.setText("Surtidor 8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 90, -1));

        jLabel9.setText("Coches esperando fuerda de la gasolinera:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        op1.setEditable(false);
        op1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, -1));

        jLabel10.setText("Operado por:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, -1));

        op2.setEditable(false);
        op2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 130, -1));

        op3.setEditable(false);
        op3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 130, -1));

        op4.setEditable(false);
        op4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 130, -1));

        op5.setEditable(false);
        op5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, -1));

        op6.setEditable(false);
        op6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 130, -1));

        op7.setEditable(false);
        op7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 130, -1));

        op8.setEditable(false);
        op8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(op8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 130, -1));

        jLabel11.setText("Operado por:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel12.setText("Operado por:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel13.setText("Operado por:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        jLabel14.setText("Operado por:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        jLabel15.setText("Operado por:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel16.setText("Operado por:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLabel17.setText("Operado por:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        su2.setEditable(false);
        su2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 130, 40));

        su1.setEditable(false);
        su1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(su1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 40));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("GASOLINERA - DISTRIBUCIÓN");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 410, 40));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 20, 20));

        io4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io4.setEnabled(false);
        getContentPane().add(io4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, 50, 40));

        iv2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv2.setEnabled(false);
        getContentPane().add(iv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 50, 40));

        iv3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv3.setEnabled(false);
        getContentPane().add(iv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 50, 40));

        iv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv4.setEnabled(false);
        getContentPane().add(iv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 50, 40));

        iv5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv5.setEnabled(false);
        getContentPane().add(iv5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 50, 40));

        iv6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv6.setEnabled(false);
        getContentPane().add(iv6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 50, 40));

        iv7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv7.setEnabled(false);
        getContentPane().add(iv7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 50, 40));

        iv8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv8.setEnabled(false);
        getContentPane().add(iv8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, 50, 40));

        iv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconVehiculo.png"))); // NOI18N
        iv1.setEnabled(false);
        getContentPane().add(iv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 50, 40));

        io8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io8.setEnabled(false);
        getContentPane().add(io8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 50, 40));

        io2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io2.setEnabled(false);
        getContentPane().add(io2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 50, 40));

        io3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io3.setEnabled(false);
        getContentPane().add(io3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 50, 40));

        io1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io1.setEnabled(false);
        getContentPane().add(io1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 50, 40));

        io5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io5.setEnabled(false);
        getContentPane().add(io5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 50, 40));

        io6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io6.setEnabled(false);
        getContentPane().add(io6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 50, 40));

        io7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconOperario.png"))); // NOI18N
        io7.setEnabled(false);
        getContentPane().add(io7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 50, 40));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icon.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 60, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteInterfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel io1;
    private javax.swing.JLabel io2;
    private javax.swing.JLabel io3;
    private javax.swing.JLabel io4;
    private javax.swing.JLabel io5;
    private javax.swing.JLabel io6;
    private javax.swing.JLabel io7;
    private javax.swing.JLabel io8;
    private javax.swing.JLabel iv1;
    private javax.swing.JLabel iv2;
    private javax.swing.JLabel iv3;
    private javax.swing.JLabel iv4;
    private javax.swing.JLabel iv5;
    private javax.swing.JLabel iv6;
    private javax.swing.JLabel iv7;
    private javax.swing.JLabel iv8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCochesEsperando;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextField op3;
    private javax.swing.JTextField op4;
    private javax.swing.JTextField op5;
    private javax.swing.JTextField op6;
    private javax.swing.JTextField op7;
    private javax.swing.JTextField op8;
    private javax.swing.JTextField su1;
    private javax.swing.JTextField su2;
    private javax.swing.JTextField su3;
    private javax.swing.JTextField su4;
    private javax.swing.JTextField su5;
    private javax.swing.JTextField su6;
    private javax.swing.JTextField su7;
    private javax.swing.JTextField su8;
    // End of variables declaration//GEN-END:variables
}
